name: nombre_contenedor
services:
  springboot-app:
  build:
  context: .
  dockerfile: Dockerfile
  ports:
    - "8007:8007"
  networks:
    - my_bridge_network
networks:
  my_bridge_network:
  external: true