name: modulo-07
services:
  postgresql:
    image: postgres:14.8
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB" ]
      interval: 10s
      retries: 3

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    networks:
      - my_bridge_network
networks:
  my_bridge_network:
    external: true